apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: energiveiledning
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oslokommune/energiveiledning.git
    targetRevision: main
    path: deploy/marvin
  destination:
    server: https://kubernetes.default.svc
    namespace: energiveiledning
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
