apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: energiveiledning-secrets
  namespace: energiveiledning
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kv-energiveiledning
    kind: SecretStore
  target:
    name: energiveiledning-secrets
    creationPolicy: Owner
  data:
    - secretKey: MATRIKKEL_USERNAME
      remoteRef:
        key: matrikkel-username
    - secretKey: MATRIKKEL_PASSWORD
      remoteRef:
        key: matrikkel-password
    - secretKey: MATRIKKEL_API_BASE_URL_PROD
      remoteRef:
        key: matrikkel-base-url-prod
    - secretKey: MATRIKKEL_API_BASE_URL_TEST
      remoteRef:
        key: matrikkel-base-url-test
    - secretKey: ENOVA_API_KEY
      remoteRef:
        key: enova-api-key
