apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kv-energiveiledning
  namespace: energiveiledning
spec:
  provider:
    azurekv:
      tenantId: "<azure-tenant-id>"
      vaultUrl: "https://<keyvault-navn>.vault.azure.net/"
      authType: WorkloadIdentity
